### ISSUE TITLE
what`s this?

### ISSUE THREAD

**Issue by ronewird** [alkarinv/BattleArena#120]
2013-03-09 13:39:16 [SEVERE] [BA:Error] method=public void mc.alk.arena.controllers.BattleArenaController.onPlayerInteract(org.bukkit.event.player.PlayerInteractEvent),  types.length=1,  p=CraftPlayer{name=Gliardolone},  listener=[BattleArenaController : [MEM onPlayerInteract, PlayerInteractEvent p=HIGHEST preReqs:onFinish   playerMethod=public final org.bukkit.entity.Player org.bukkit.event.player.PlayerEvent.getPlayer()]]
2013-03-09 13:39:16 [SEVERE] java.lang.reflect.InvocationTargetException
2013-03-09 13:39:16 [SEVERE]    at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source)
2013-03-09 13:39:16 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-03-09 13:39:16 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
2013-03-09 13:39:16 [SEVERE]    at mc.alk.arena.listeners.BukkitEventListener.doMethods(BukkitEventListener.java:263)
2013-03-09 13:39:16 [SEVERE]    at mc.alk.arena.listeners.BukkitEventListener.callListeners(BukkitEventListener.java:233)
2013-03-09 13:39:16 [SEVERE]    at mc.alk.arena.listeners.BukkitEventListener.doSpecificPlayerEvent(BukkitEventListener.java:226)
2013-03-09 13:39:16 [SEVERE]    at mc.alk.arena.listeners.BAEventListener$1.execute(BAEventListener.java:43)
2013-03-09 13:39:16 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-03-09 13:39:16 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-03-09 13:39:16 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2013-03-09 13:39:16 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:178)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.PlayerInteractManager.dig(PlayerInteractManager.java:114)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:564)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.Packet14BlockDig.handle(SourceFile:46)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.NetworkManager.b(NetworkManager.java:290)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:113)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:30)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:598)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)
2013-03-09 13:39:16 [SEVERE]    at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)

**Comment by darrenstraight** [comment]
When does it happen? Any specific command? or time in the arena?

**Comment by ronewird** [comment]
no idea i was at work, I just see on the log when i come back at home...
That`s strange becouse my server is running fast e without lag. I have tray to take out battle tag plugin, it look a little big bugged..

Any good advice for investigation?

**Comment by ronewird** [comment]
ok. No problem :D
thank`s for your help.

Was the problem of the iron block i have just find one of my player at work to find a way to remove that iron block and i have find a lot of error in my console. Memory usage around 31%. Is amazing how a simple bug can slown down the system and give trouble in any perfect build plugin configuration...

I`m learning who the best thing to do in minecraft server is to put max one plugin for mount or every 3 weeks.....just if you really need to do that....

Is quite hard after understand what kind of problem is afflicting the system.
I`m slowling learn how to manage a minecraft server.

I fix it just with the new upgrade of Ba. Thanks at the developer!
