### ISSUE TITLE
Minor Null Pointer Error

### ISSUE THREAD

**Issue by UltraFaceguy** [alkarinv/BattleArena#163]
2013-05-05 04:01:28 [SEVERE] [BattleArena] Error setting currency name through vault
2013-05-05 04:01:29 [SEVERE] java.lang.NullPointerException
2013-05-05 04:01:29 [SEVERE]    at cosine.boseconomy.BOSEconomy.getMoneyName(BOSEconomy.java:962)
2013-05-05 04:01:29 [SEVERE]    at net.milkbowl.vault.economy.plugins.Economy_BOSE7.currencyNameSingular(Economy_BOSE7.java:120)
2013-05-05 04:01:29 [SEVERE]    at mc.alk.arena.controllers.MoneyController.setEconomy(MoneyController.java:77)
2013-05-05 04:01:29 [SEVERE]    at mc.alk.arena.listeners.BAPluginListener.loadVault(BAPluginListener.java:252)
2013-05-05 04:01:29 [SEVERE]    at mc.alk.arena.listeners.BAPluginListener.loadAll(BAPluginListener.java:87)
2013-05-05 04:01:29 [SEVERE]    at mc.alk.arena.BattleArena.onEnable(BattleArena.java:128)
2013-05-05 04:01:29 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-05-05 04:01:29 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:375)
2013-05-05 04:01:29 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
2013-05-05 04:01:29 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:309)
2013-05-05 04:01:29 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:291)
2013-05-05 04:01:29 [SEVERE]    at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:315)
2013-05-05 04:01:29 [SEVERE]    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:294)
2013-05-05 04:01:29 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:254)
2013-05-05 04:01:29 [SEVERE]    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:149)
2013-05-05 04:01:29 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:393)
2013-05-05 04:01:29 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:573)
2013-05-05 04:01:29 [INFO] [BattleArena] found economy plugin Vault. [Default]

That happens every time I start up the server. Nothing too serious, doesn't effect much, but thought you ought to know.

**Comment by alkarinv** [comment]
Yeah, BOSE doesn't use that method, so it always throws that.  I don't want to get rid of the message though in case a more serious error ever comes up.  You should tell BOSE to implement that method correctly :)
