### ISSUE TITLE
An error log about "limit of 32 characters"

### ISSUE THREAD

**Issue by ghost** [alkarinv/BattleArena#167]
2013-05-13 20:58:00 [SEVERE] java.lang.IllegalArgumentException: Display name 'Free_Sugar, ZhaoRenhao, brian31321, jacky10045, kuhchunki' is longer than the limit of 32 characters
2013-05-13 20:58:00 [SEVERE]    at org.apache.commons.lang.Validate.isTrue(Validate.java:157)
2013-05-13 20:58:00 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R2.scoreboard.CraftTeam.setDisplayName(CraftTeam.java:37)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.scoreboard.BukkitScoreboard.addTeam(BukkitScoreboard.java:86)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match.addTeam(Match.java:718)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match.onJoin(Match.java:837)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match.onJoin(Match.java:829)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.getMatchAndRemove(ArenaMatchQueue.java:417)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch(ArenaMatchQueue.java:388)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch(ArenaMatchQueue.java:282)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.notifyIfNeeded(ArenaMatchQueue.java:177)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.notifyIfNeeded(ArenaMatchQueue.java:168)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.add(ArenaMatchQueue.java:86)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.controllers.BattleArenaController.matchFinished(BattleArenaController.java:217)
2013-05-13 20:58:00 [SEVERE]    at sun.reflect.GeneratedMethodAccessor461.invoke(Unknown Source)
2013-05-13 20:58:00 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-05-13 20:58:00 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.controllers.MethodController.callEvent(MethodController.java:427)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.controllers.MethodController.callEvent(MethodController.java:418)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.Competition.callEvent(Competition.java:147)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match.deconstruct(Match.java:668)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match.access$500(Match.java:98)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match$MatchCompleted$1.run(Match.java:615)
2013-05-13 20:58:00 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftTask.run(CraftTask.java:53)
2013-05-13 20:58:00 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2013-05-13 20:58:00 [SEVERE]    at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:512)
2013-05-13 20:58:00 [SEVERE]    at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
2013-05-13 20:58:00 [SEVERE]    at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
2013-05-13 20:58:00 [SEVERE]    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
2013-05-13 20:58:00 [SEVERE]    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
2013-05-13 20:58:00 [SEVERE] java.lang.IllegalArgumentException: Display name 'Pear_bucket, TNTter, Zhaoyi, momocat, pig2208' is longer than the limit of 32 characters
2013-05-13 20:58:00 [SEVERE]    at org.apache.commons.lang.Validate.isTrue(Validate.java:157)
2013-05-13 20:58:00 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R2.scoreboard.CraftTeam.setDisplayName(CraftTeam.java:37)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.scoreboard.BukkitScoreboard.addTeam(BukkitScoreboard.java:86)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match.addTeam(Match.java:718)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match.onJoin(Match.java:837)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match.onJoin(Match.java:829)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.getMatchAndRemove(ArenaMatchQueue.java:417)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch(ArenaMatchQueue.java:388)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch(ArenaMatchQueue.java:282)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.notifyIfNeeded(ArenaMatchQueue.java:177)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.notifyIfNeeded(ArenaMatchQueue.java:168)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.add(ArenaMatchQueue.java:86)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.controllers.BattleArenaController.matchFinished(BattleArenaController.java:217)
2013-05-13 20:58:00 [SEVERE]    at sun.reflect.GeneratedMethodAccessor461.invoke(Unknown Source)
2013-05-13 20:58:00 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-05-13 20:58:00 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.controllers.MethodController.callEvent(MethodController.java:427)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.controllers.MethodController.callEvent(MethodController.java:418)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.Competition.callEvent(Competition.java:147)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match.deconstruct(Match.java:668)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match.access$500(Match.java:98)
2013-05-13 20:58:00 [SEVERE]    at mc.alk.arena.competition.match.Match$MatchCompleted$1.run(Match.java:615)
2013-05-13 20:58:01 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftTask.run(CraftTask.java:53)
2013-05-13 20:58:01 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2013-05-13 20:58:01 [SEVERE]    at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:512)
2013-05-13 20:58:01 [SEVERE]    at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
2013-05-13 20:58:01 [SEVERE]    at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
2013-05-13 20:58:01 [SEVERE]    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
2013-05-13 20:58:01 [SEVERE]    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)

**Comment by ghost** [comment]
BattleArena v3.8.7.5
CraftBukkit 1.5.1 R0.2

**Comment by alkarinv** [comment]
This should be fixed in the newest versions of BattleArena 3.8.8+
