### ISSUE TITLE
 [BattleArena] Task #29 for BattleArena v3.9.1.3 generated an exception

### ISSUE THREAD

**Issue by MaxCoffeebreath** [alkarinv/BattleArena#189]
2013-07-19 21:55:46 [INFO] [BattleArena] Enabling BattleArena v3.9.1.3
2013-07-19 21:55:46 [INFO] [0;31;22m[BattleArena] [0;33;22mv3.9.1.3[0;37;1m enabling![m
2013-07-19 21:55:46 [INFO] [BattleArena] BattleTracker not detected, not tracking wins
2013-07-19 21:55:46 [INFO] [BattleArena] Essentials detected. God mode handling activated
2013-07-19 21:55:46 [INFO] [BattleArena] WorldEdit detected.
2013-07-19 21:55:46 [INFO] [BattleArena] WorldGuard detected. WorldGuard regions can now be used
2013-07-19 21:55:46 [INFO] [BattleArena] found economy plugin Vault. [Default]
2013-07-19 21:55:46 [INFO] [BattleArena] no additional Arena modules
2013-07-19 21:55:47 [INFO] [BattleArena] registering classes: duelist, gladiator, archer, monk
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [BattleArena] Loaded Skirmish params
2013-07-19 21:55:47 [INFO] [BattleArena] No arenas found for   arenatype=Skirmish  cs=
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [BattleArena] Loaded FreeForAll params
2013-07-19 21:55:47 [INFO] [BattleArena] No arenas found for   arenatype=FreeForAll  cs=
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [BattleArena] Loaded Arena params
2013-07-19 21:55:47 [INFO] [BattleArena] Loaded Arena arenas: dueling1
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [BattleArena] Loaded DeathMatch params
2013-07-19 21:55:47 [INFO] [BattleArena] No arenas found for   arenatype=DeathMatch  cs=
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [BattleArena] Loaded Colosseum params
2013-07-19 21:55:47 [INFO] [BattleArena] No arenas found for   arenatype=Colosseum  cs=
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [BattleArena] Loaded Battleground params
2013-07-19 21:55:47 [INFO] [BattleArena] Loaded Battleground arenas: sky
2013-07-19 21:55:47 [INFO] [BattleArena] Loaded Duel params
2013-07-19 21:55:47 [INFO] [BattleArena] No arenas found for   arenatype=Duel  cs=
2013-07-19 21:55:47 [INFO] [BattleArena] Loaded Tourney params
2013-07-19 21:55:47 [INFO] [0;31;22m[BattleArena] [0;33;22mv3.9.1.3[0;37;1m enabled![m
2013-07-19 21:55:47 [INFO] [PluginUpdater] BattleArena v3.9.1.3 checking for updates
2013-07-19 21:55:47 [INFO] [SurvivalArena] Enabling SurvivalArena v0.9.2
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [SurvivalArena] Loaded SurvivalArena params
2013-07-19 21:55:47 [INFO] [SurvivalArena] No arenas found for   arenatype=SurvivalArena  cs=
2013-07-19 21:55:47 [INFO] [SurvivalArena] v0.9.2 enabled
2013-07-19 21:55:47 [INFO] [ArenaPaintball] Enabling ArenaPaintball v1.1.3
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [ArenaPaintball] Loaded Paintball params
2013-07-19 21:55:47 [INFO] [ArenaPaintball] Loaded Paintball arenas: Paintball1
2013-07-19 21:55:47 [INFO] [ArenaPaintball] v1.1.3 enabled!
2013-07-19 21:55:47 [INFO] [ArenaFutbol] Enabling ArenaFutbol v0.3.8
2013-07-19 21:55:47 [INFO] [ArenaFutbol] loading ArenaFutbol v0.3.8
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [ArenaFutbol] Loaded Futbol params
2013-07-19 21:55:47 [INFO] [ArenaFutbol] Loaded Futbol arenas: Stadium1
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [ArenaFutbol] Loaded MaxFutbol params
2013-07-19 21:55:47 [INFO] [ArenaFutbol] No arenas found for   arenatype=MaxFutbol  cs=
2013-07-19 21:55:47 [INFO] [ArenaSpleef] Enabling ArenaSpleef v1.4.4
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [ArenaSpleef] Loaded Spleef params
2013-07-19 21:55:47 [INFO] [ArenaSpleef] Loaded Spleef arenas: spleef_arena1
2013-07-19 21:55:47 [INFO] [ArenaSpleef] v1.4.4 enabled!
2013-07-19 21:55:47 [INFO] [ArenaCTF] Enabling ArenaCTF v1.2.7
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [ArenaCTF] Loaded CaptureTheFlag params
2013-07-19 21:55:47 [INFO] [ArenaCTF] No arenas found for   arenatype=CaptureTheFlag  cs=
2013-07-19 21:55:47 [INFO] [ArenaCTF] v1.2.7 enabled!
2013-07-19 21:55:47 [INFO] [ArenaBowSpleef] Enabling ArenaBowSpleef v0.1
2013-07-19 21:55:47 [SEVERE] Couldn't add tracker interface
2013-07-19 21:55:47 [INFO] [ArenaBowSpleef] Loaded BowSpleef params
2013-07-19 21:55:47 [INFO] [ArenaBowSpleef] Loaded BowSpleef arenas: Bowspleef1
2013-07-19 21:55:47 [INFO] [ArenaBowSpleef] v0.1 enabled!
2013-07-19 21:55:47 [INFO] Server permissions file permissions.yml is empty, ignoring it
2013-07-19 21:55:47 [INFO] Done (12.514s)! For help, type "help" or "?"
2013-07-19 21:55:47 [INFO] Starting GS4 status listener
2013-07-19 21:55:47 [INFO] Query running on 192.168.15.21:17770
2013-07-19 21:55:51 [WARNING] [BattleArena] Task #29 for BattleArena v3.9.1.3 generated an exception
java.lang.NullPointerException
    at mc.alk.arena.serializers.SignSerializer.loadAll(SignSerializer.java:26)
    at mc.alk.arena.BattleArena$1.run(BattleArena.java:214)
    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:58)
    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:518)
    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:239)
    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:481)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:413)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)

**Comment by MaxCoffeebreath** [comment]
Apparently this was due to a bad sign, which ties to the question I put on the Wiki.... how do you remove one of the 'command signs' signs created with this plugin?  If someone made a mistake or wishes to move the sign they need to be able to remove them.

**Comment by alkarinv** [comment]
I think its a bad sign, but here is a version that has a fix for that.

https://dl.dropboxusercontent.com/u/38069770/jars/BattleArena.jar

For the command signs... honestly I've been breaking the block behind or underneath the sign.  But, I'll make it so users with op or "arena.admin" break the signs when left clicking.

**Comment by alkarinv** [comment]
I'm going to close this as I think that will fix, just reopen if it doesnt!
