### ISSUE TITLE
Issue with Battlearena after a duel, severely lags the server.

### ISSUE THREAD

**Issue by Yukiaro** [alkarinv/BattleArena#200]
2013-08-05 09:17:15 [INFO] [0;33;22m[0;33;22m[Arena][0;33;1m [0;37;22mseth1933[0;33;1m[1250][0;33;22m vs [0;37;22mKoloRed[0;33;1m[1225][0;33;22m![m
[SEVERE] java.lang.ClassCastException: mc.alk.arena.objects.stats.BlankArenaStat cannot be cast to mc.alk.arena.objects.stats.TrackerArenaStat
[SEVERE]    at mc.alk.arena.objects.stats.TrackerArenaStat.getLossesVersus(TrackerArenaStat.java:24)
[SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.formatTwoTeamsOptions(MessageFormatter.java:218)
[SEVERE]    at mc.alk.arena.serializers.MessageSerializer.sendVictory(MessageSerializer.java:182)
[SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendOnVictoryMsg(MatchMessageImpl.java:110)
[SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessager.sendOnVictoryMsg(MatchMessager.java:46)
[SEVERE]
mc.alk.arena.competition.match.Match$MatchVictory.run(Match.java:562)
[SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:53)
[SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
[SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:522)
[SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
[SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
[SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
[SEVERE]    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
[SEVERE] java.lang.ClassCastException: mc.alk.arena.objects.stats.BlankArenaStat cannot be cast to mc.alk.arena.objects.stats.TrackerArenaStat
[SEVERE]    at mc.alk.arena.objects.stats.TrackerArenaStat.getWinsVersus(TrackerArenaStat.java:17)
[SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.formatTwoTeamsOptions(MessageFormatter.java:203)
[SEVERE]    at mc.alk.arena.serializers.MessageSerializer.sendVictory(MessageSerializer.java:182)
[SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendOnVictoryMsg(MatchMessageImpl.java:110)
[SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessager.sendOnVictoryMsg(MatchMessager.java:46)
[SEVERE]    at mc.alk.arena.competition.match.Match$MatchVictory.run(Match.java:562)
[SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:53)
[SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
[SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:522)
[SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
[SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
[SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
[SEVERE]    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)

**Comment by alkarinv** [comment]
Ugh, Sorry man.. I'll try to get a fix for this right away.. I was busy the past 2 days, but I'll have time tomorrow to fix this up.

**Comment by Yukiaro** [comment]
I appreciate it man! usually my console errors are from something I did and I'm able to fix it but this one was frustrating! I hope it isn't too difficult for you to fix.

Good luck man :3

**Comment by alkarinv** [comment]
Hey, so I wasnt able to get to it today.. but tomorrow!! sorry for the delay

**Comment by Yukiaro** [comment]
Nah man take your time I really appreciate your time on this, I run a fairly big pvp clan on minecraft and we go across multiple servers.  So I know how it is to have a bunch of people asking for things and how stressful it can be.

Take your time I am in no rush.

**Comment by alkarinv** [comment]
Hey Yukiaro,

Could you try this. 

http://dev.bukkit.org/media/files/726/125/BattleArena.jar

That should fix that problem.

**Comment by Yukiaro** [comment]
Okay so I had thought it was fixed as everything was working perfectly until I noticed that the regions weren't regenerating when the arenas ended, so I looked further into this and tried recreating the worldguard region and got an ingame error message saying "Region Added! Adding WorldGuard Region failed! null" In the console I have this error.

Is this a problem on my side or with the new jar? 

2013-08-14 21:47:40 [SEVERE] java.lang.NullPointerException
2013-08-14 21:47:40 [SEVERE]    at mc.alk.arena.util.WorldGuardUtil.setFlag(WorldGuardUtil.java:162)
2013-08-14 21:47:40 [SEVERE]    at mc.alk.arena.controllers.WorldGuardController.setFlag(WorldGuardController.java:91)
2013-08-14 21:47:40 [SEVERE]    at mc.alk.arena.controllers.ArenaAlterController.addWorldGuardRegion(ArenaAlterController.java:216)
2013-08-14 21:47:40 [SEVERE]    at mc.alk.arena.controllers.ArenaAlterController.setArenaOption(ArenaAlterController.java:145)
2013-08-14 21:47:40 [SEVERE]    at mc.alk.arena.executors.BAExecutor.arenaSetOption(BAExecutor.java:909)
2013-08-14 21:47:40 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-08-14 21:47:40 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-08-14 21:47:40 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-08-14 21:47:40 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-08-14 21:47:40 [SEVERE]    at mc.alk.arena.executors.BaseExecutor.onCommand(BaseExecutor.java:253)
2013-08-14 21:47:40 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-08-14 21:47:40 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:191)
2013-08-14 21:47:40 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:962)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:880)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:837)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
2013-08-14 21:47:40 [SEVERE]    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)

**Comment by alkarinv** [comment]
Hey Yukiaro,

http://dev.bukkit.org/media/files/726/565/BattleArena.jar

That has a fix for the worldguard regions.  Any other problems besides that?

**Comment by Yukiaro** [comment]
Worldguard and the issue I had before with arena duels are working great.

I appreciate the help man!  Again, thank you so much.

**Comment by alkarinv** [comment]
Great! thanks for let me know about the problems.
