### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by creptor** [alkarinv/BattleArena#236]
30.12 08:15:29 [Server] WARNING Can't keep up! Did the system time change, or is the server overloaded?
30.12 08:15:29 [Server] SEVERE at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
30.12 08:15:29 [Server] SEVERE at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:421)
30.12 08:15:29 [Server] SEVERE at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:488)
30.12 08:15:29 [Server] SEVERE at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:227)
30.12 08:15:29 [Server] SEVERE at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:524)
30.12 08:15:29 [Server] SEVERE at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
30.12 08:15:29 [Server] SEVERE at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:53)
30.12 08:15:29 [Server] SEVERE at mc.alk.arena.controllers.APIRegistrationController$DelayedRegistrationHandler.run(APIRegistrationController.java:67)
30.12 08:15:29 [Server] SEVERE at mc.alk.arena.controllers.APIRegistrationController.registerCompetition(APIRegistrationController.java:169)
30.12 08:15:29 [Server] SEVERE at mc.alk.arena.controllers.APIRegistrationController._registerCompetition(APIRegistrationController.java:218)
30.12 08:15:29 [Server] SEVERE at mc.alk.arena.serializers.ConfigSerializer.getArenaType(ConfigSerializer.java:366)
30.12 08:15:29 [Server] SEVERE java.lang.NullPointerException
30.12 08:15:29 [Server] INFO ------- BattleArena  ac= null

**Comment by creptor** [comment]
The full log: http://pastebin.com/eFPW1KVF

**Comment by creptor** [comment]
Ups, sorry It was a problem with the config
