### ISSUE TITLE
Did it not create the folder and files? o.0

### ISSUE THREAD

**Issue by EMOberger** [alkarinv/BattleArena#3]
2012-09-11 21:51:07 [INFO] [BattleArena] Enabling BattleArena v3.6.4
2012-09-11 21:51:07 [INFO] [BattleArena v3.6.4] starting enable!
2012-09-11 21:51:07 [SEVERE] java.io.IOException: The system cannot find the path specified
2012-09-11 21:51:07 [SEVERE]    at java.io.WinNTFileSystem.createFileExclusively(Native Method)
2012-09-11 21:51:07 [SEVERE]    at java.io.File.createNewFile(Unknown Source)
2012-09-11 21:51:07 [SEVERE]    at mc.alk.arena.serializers.BaseSerializer.setConfig(BaseSerializer.java:34)
2012-09-11 21:51:07 [SEVERE]    at mc.alk.arena.BattleArena.onEnable(BattleArena.java:94)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:283)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:265)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:297)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:276)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:226)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:379)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
2012-09-11 21:51:07 [SEVERE] java.io.FileNotFoundException: plugins\BattleArena\messages.yml (The system cannot find the path specified)
2012-09-11 21:51:07 [SEVERE]    at java.io.FileInputStream.open(Native Method)
2012-09-11 21:51:07 [SEVERE]    at java.io.FileInputStream.<init>(Unknown Source)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
2012-09-11 21:51:07 [SEVERE]    at mc.alk.arena.serializers.BaseSerializer.setConfig(BaseSerializer.java:42)
2012-09-11 21:51:07 [SEVERE]    at mc.alk.arena.BattleArena.onEnable(BattleArena.java:94)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:283)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:265)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:297)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:276)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:226)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:379)
2012-09-11 21:51:07 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
2012-09-11 21:51:07 [WARNING] Updating to messages.yml version 1.1
2012-09-11 21:51:07 [WARNING] If you had custom changes to messages you will have to redo them
2012-09-11 21:51:07 [WARNING] You can now override specific match/event messages inside the messages folder
2012-09-11 21:51:07 [SEVERE] java.io.IOException: The system cannot find the path specified
2012-09-11 21:51:07 [SEVERE]    at java.io.WinNTFileSystem.createFileExclusively(Native Method)
2012-09-11 21:51:07 [SEVERE]    at java.io.File.createNewFile(Unknown Source)
2012-09-11 21:51:07 [SEVERE]    at mc.alk.arena.serializers.BaseSerializer.setConfig(BaseSerializer.java:34)
2012-09-11 21:51:07 [SEVERE]    at mc.alk.arena.serializers.YamlFileUpdater.updateMessageSerializer(YamlFileUpdater.java:191)
2012-09-11 21:51:07 [SEVERE]    at mc.alk.arena.BattleArena.onEnable(BattleArena.java:95)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2012-09-11 21:51:07 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
2012-09-11 21:51:08 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2012-09-11 21:51:08 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:283)
2012-09-11 21:51:08 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:265)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:297)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:276)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:226)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:379)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
2012-09-11 21:51:08 [SEVERE] java.io.FileNotFoundException: plugins\BattleArena\messages.yml (The system cannot find the path specified)
2012-09-11 21:51:08 [SEVERE]    at java.io.FileInputStream.open(Native Method)
2012-09-11 21:51:08 [SEVERE]    at java.io.FileInputStream.<init>(Unknown Source)
2012-09-11 21:51:08 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
2012-09-11 21:51:08 [SEVERE]    at mc.alk.arena.serializers.BaseSerializer.setConfig(BaseSerializer.java:42)
2012-09-11 21:51:08 [SEVERE]    at mc.alk.arena.serializers.YamlFileUpdater.updateMessageSerializer(YamlFileUpdater.java:191)
2012-09-11 21:51:08 [SEVERE]    at mc.alk.arena.BattleArena.onEnable(BattleArena.java:95)
2012-09-11 21:51:08 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2012-09-11 21:51:08 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
2012-09-11 21:51:08 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2012-09-11 21:51:08 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:283)
2012-09-11 21:51:08 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:265)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:297)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:276)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:226)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:379)
2012-09-11 21:51:08 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
2012-09-11 21:51:08 [SEVERE] Error occurred while enabling BattleArena v3.6.4 (Is it up to date?)
java.lang.NoClassDefFoundError: mc/alk/tracker/objects/Stat
    at mc.alk.arena.BattleArena.onEnable(BattleArena.java:99)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:283)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:265)
    at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:297)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:276)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:226)
    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:379)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.ClassNotFoundException: mc.alk.tracker.objects.Stat
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:44)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 12 more

**Comment by alkarinv** [comment]
Well there might be two errors there.  But the main one is I accidentally left in a dependency on BattleTracker. 
http://dev.bukkit.org/server-mods/battletracker/

I try not to do that but sometimes I forget to test without it in.  I'll see if I can get you a version up here in like 30 min.

**Comment by alkarinv** [comment]
Here is an updated jar.  Let me know if that has any errors.  3.6.4.5

https://github.com/downloads/alkarinv/BattleArena/BattleArena.jar

**Comment by EMOberger** [comment]
That fixed everything, no errors now, thanks

**Comment by alkarinv** [comment]
Good to hear that worked, and sorry about that.

In other news, I will be releasing another version tonight with multiple fixes and improvements..
