### ISSUE TITLE
 Error occurred while enabling BattleArena v3.9.7.9

### ISSUE THREAD

**Issue by dzoome** [alkarinv/BattleArena#311]
Hi :-)
I become this error:

[the server have this WorldGuard Version: [19:41:15] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.0.0-beta-03.1514-

[19:41:30] [Server thread/ERROR]: Error occurred while enabling BattleArena v3.9.7.9 (Is it up to date?)
java.lang.VerifyError: (class: mc/alk/arena/util/plugins/WorldGuardUtil, method: pasteSchematic signature: (Lorg/bukkit/command/CommandSender;Lcom/sk89q/worldguard/protection/regions/ProtectedRegion;Ljava/lang/String;Lorg/bukkit/World;)Z) Incompatible argument to function
    at mc.alk.arena.controllers.plugins.WorldGuardController.setWorldGuard(WorldGuardController.java:82) ~[?:?]
    at mc.alk.arena.listeners.BAPluginListener.loadWorldGuard(BAPluginListener.java:269) ~[?:?]
    at mc.alk.arena.listeners.BAPluginListener.loadAll(BAPluginListener.java:101) ~[?:?]
    at mc.alk.arena.BattleArena.onEnable(BattleArena.java:167) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:455) [craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:389) [craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:352) [craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:326) [craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:282) [craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
    at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:182) [craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436) [craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]
    at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit-dev.jar:git-Bukkit-1.7.9-R0.2-11-g3fd9db2-b3098jnks]

Please help me.
lg Dominik

**Comment by Europia79** [comment]
Your BattleArena v3.9.7.9 is out-of-date. This is an easy fix: Just update BattleArena at

http://dev.bukkit.org/bukkit-plugins/battlearena2/

http://dev.bukkit.org/bukkit-plugins/battlearena2/files/11-battle-arena-v3-9-9-18/
