### ISSUE TITLE
Several ongoing matches, pauses.

### ISSUE THREAD

**Issue by freakyy85** [alkarinv/BattleArena#60]
/tourney auto arena <-- some hours before I did: /tourney auto pb (paintball arena doesnt seem to get finished even though there was a winner)

After some matches:

2012-11-03 04:14:47 [INFO] ^[[33;22m[Arena Tourney] ^[[37;22mblitson^[[33;1m[1258] ^[[33;22m(1:1)^[[33;1m defeated ^[[37;22mTagapple^[[33;1m[1223] ^[[33;22m(0:1)!^[[m
2012-11-03 04:14:56 [INFO] ^[[33;22m^[[37;1m[Paintball Tourney] ^[[37;22malfadude314^[[33;1m[1403]^[[33;22m vs ^[[37;22mAwesome_Gurl123^[[33;1m[1250]^[[33;22m!^[[m
2012-11-03 04:15:12 [INFO] ^[[33;22m^[[33;22m[Arena Tourney] ^[[37;22mTagapple^[[33;1m[1223]^[[33;22m vs ^[[37;22mblitson^[[33;1m[1258]^[[33;22m!^[[m
2012-11-03 04:15:19 [INFO] ^[[37;1m[Paintball Tourney] ^[[37;22mAwesome_Gurl123^[[33;1m[1285] ^[[33;22m(1:0)^[[33;1m defeated ^[[37;22malfadude314^[[33;1m[1367] ^[[33;22m(22:7)!^[[m
2012-11-03 04:19:48 [INFO] ^[[33;22m^[[37;1m[Paintball Tourney] ^[[37;22malfadude314^[[33;1m[1367]^[[33;22m vs ^[[37;22mlegodude4066^[[33;1m[1273]^[[33;22m!^[[m
2012-11-03 04:19:52 [INFO] ^[[33;22m[Arena Tourney] ^[[37;22mbigbangjoe^[[33;1m[1296] ^[[33;22m(2:0)^[[33;1m defeated ^[[37;22mTagapple^[[33;1m[1201] ^[[33;22m(0:2)!^[[m
2012-11-03 04:19:57 [INFO] ^[[33;22m[Arena Tourney]^[[33;1m Congratulations to ^[[33;22mbigbangjoe^[[33;1m for winning!^[[m
2012-11-03 04:19:57 [INFO] ^[[33;22m[Arena Tourney]^[[33;1m Congratulations to ^[[33;22m^[[37;22mbigbangjoe^[[33;1m[1296] ^[[33;22m(2:0)^[[33;1m for winning!!^[[m
2012-11-03 04:20:07 [INFO] ^[[37;1m[Paintball Tourney] ^[[37;22mlegodude4066^[[33;1m[1304] ^[[33;22m(2:0)^[[33;1m defeated ^[[37;22malfadude314^[[33;1m[1335] ^[[33;22m(22:8)!^[[m

Somewhere in here between there was a big break before any comming matches were announced.
Means in the middle of the tourney, all stopped. And then suddenly it continued some time later.

It tells me for /tourney cancel that several events are running. Doing /tourney ongoing says command doesnt exist. /arena cancel all -> then /tourney cancel still says several events are running. I didnt start two events at the same time.

Also:
2012-11-03 04:16:36 [INFO] alfadude314 issued server command: /tourney leave
2012-11-03 04:16:36 [SEVERE] java.lang.reflect.InvocationTargetException
2012-11-03 04:16:36 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-11-03 04:16:36 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2012-11-03 04:16:36 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2012-11-03 04:16:36 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
2012-11-03 04:16:36 [SEVERE]    at mc.alk.arena.executors.CustomCommandExecutor.onCommand(CustomCommandExecutor.java:169)
2012-11-03 04:16:36 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2012-11-03 04:16:36 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:185)
2012-11-03 04:16:36 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:528)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:913)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:824)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:806)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:111)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.ServerConnection.b(SourceFile:35)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:570)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:487)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
2012-11-03 04:16:36 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
2012-11-03 04:16:36 [SEVERE] Caused by: java.lang.NullPointerException
2012-11-03 04:16:36 [SEVERE]    at mc.alk.arena.executors.EventExecutor.eventLeave(EventExecutor.java:146)
2012-11-03 04:16:36 [SEVERE]    ... 21 more

**Comment by alkarinv** [comment]
Hey Freaky, I will definitely clean this up this code. When I made multiple of the same event possible at the same time I obviously screwed something up.  I have a busy day tomorrow, but I should have something fixed for you sunday at some point.

**Comment by alkarinv** [comment]
That error is just a simple null pointer exception, already fixed.  I'll put up the code that fixes it now.  You can get it in the github download section.

But the central problem is something to do with my multiple event handler, which i will have to try and fix sunday most likely.

**Comment by freakyy85** [comment]
ok cool thanks ;D

**Comment by alkarinv** [comment]
Try the most recent download here on github.  I think it should fix the problems.  Not 100% sure though so going to leave this open.

**Comment by alkarinv** [comment]
Ok, should be fixed for sure.  Fixed in v3.7.2.1+
