### ISSUE TITLE
After match players are still "In a match"

### ISSUE THREAD

**Issue by powerad23** [alkarinv/BattleArena#61]
I get: 

18:16:59 [WARNING] [BattleArena] Task #3477 for BattleArena v3.7.1 generated an
exception
java.lang.NullPointerException
        at mc.alk.arena.controllers.TeleportController.teleport(TeleportControl
er.java:112)
        at mc.alk.arena.controllers.TeleportController.teleportPlayer(TeleportC
ntroller.java:41)
        at mc.alk.arena.competition.match.PerformTransition.transition(PerformT
ansition.java:197)
        at mc.alk.arena.competition.match.PerformTransition.transition(PerformT
ansition.java:82)
        at mc.alk.arena.competition.match.PerformTransition.transition(PerformT
ansition.java:58)
        at mc.alk.arena.competition.match.Match$MatchCompleted$1.run(Match.java
348)
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(
raftScheduler.java:345)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:531)
        at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:495)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:428)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)

After my games.
How can I fix this?

**Comment by alkarinv** [comment]
So try the most recent version 3.7.1.6+, I think I have the fix for the problems I saw tonight.  Going to leave this open though until I can make sure it's stopped.

**Comment by alkarinv** [comment]
Alright, I'm going to definitely call this fixed.  If that previous version fix for some reason didnt work, v3.7.2.1+ should definitely work.
