### ISSUE TITLE
Strange things ;p

### ISSUE THREAD

**Issue by freakyy85** [alkarinv/BattleArena#62]
2012-11-05 14:22:27 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 39,695,385 milliseconds ago.  The last packet sent successfully to the server was 39,695,385 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
2012-11-05 14:22:27 [SEVERE]    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2012-11-05 14:22:27 [SEVERE]    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2012-11-05 14:22:27 [SEVERE]    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2012-11-05 14:22:27 [SEVERE]    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
2012-11-05 14:22:27 [SEVERE]    at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2012-11-05 14:22:27 [SEVERE]    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
2012-11-05 14:22:27 [SEVERE]    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3348)
2012-11-05 14:22:27 [SEVERE]    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1967)
2012-11-05 14:22:27 [SEVERE]    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2012-11-05 14:22:27 [SEVERE]    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
2012-11-05 14:22:27 [SEVERE]    at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:5022)
2012-11-05 14:22:27 [SEVERE]    at org.apache.commons.dbcp.DelegatingConnection.setAutoCommit(DelegatingConnection.java:371)
2012-11-05 14:22:27 [SEVERE]    at org.apache.commons.dbcp.DelegatingConnection.setAutoCommit(DelegatingConnection.java:371)
2012-11-05 14:22:27 [SEVERE]    at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.setAutoCommit(PoolingDataSource.java:328)
2012-11-05 14:22:27 [SEVERE]    at com.alk.serializers.SQLSerializer.getConnection(SQLSerializer.java:98)
2012-11-05 14:22:27 [SEVERE]    at com.alk.serializers.SQLSerializer.getConnection(SQLSerializer.java:91)
2012-11-05 14:22:27 [SEVERE]    at com.alk.serializers.SQLSerializer.executeQuery(SQLSerializer.java:234)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.serializers.SQLInstance.getRecord(SQLInstance.java:293)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.controllers.TrackerImpl.load(TrackerImpl.java:93)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.controllers.TrackerImpl.load(TrackerImpl.java:38)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.util.Cache.get(Cache.java:111)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.util.Cache.get(Cache.java:162)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.controllers.TrackerImpl.loadStat(TrackerImpl.java:280)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.controllers.TrackerImpl.loadRecord(TrackerImpl.java:277)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.util.BTInterface.loadRecord(BTInterface.java:44)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.util.BTInterface.loadRecord(BTInterface.java:130)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.getStat(MessageFormatter.java:345)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.formatTeamName(MessageFormatter.java:370)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.formatCommonOptions(MessageFormatter.java:99)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendMessageToTeams(MatchMessageImpl.java:60)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendOnPreStartMsg(MatchMessageImpl.java:40)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessager.sendOnPreStartMsg(MatchMessager.java:34)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.competition.match.Match.preStartMatch(Match.java:237)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.competition.match.Match.run(Match.java:191)
2012-11-05 14:22:27 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
2012-11-05 14:22:27 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:523)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:487)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
2012-11-05 14:22:27 [SEVERE] Caused by: java.net.SocketException: Broken pipe
2012-11-05 14:22:27 [SEVERE]    at java.net.SocketOutputStream.socketWrite0(Native Method)
2012-11-05 14:22:27 [SEVERE]    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
2012-11-05 14:22:27 [SEVERE]    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
2012-11-05 14:22:27 [SEVERE]    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
2012-11-05 14:22:27 [SEVERE]    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
2012-11-05 14:22:27 [SEVERE]    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3329)
2012-11-05 14:22:27 [SEVERE]    ... 34 more
2012-11-05 14:22:27 [SEVERE] Couldnt prepare statment null
2012-11-05 14:22:27 [SEVERE] java.lang.NullPointerException
2012-11-05 14:22:27 [SEVERE]    at com.alk.serializers.SQLSerializer.getStatement(SQLSerializer.java:292)
2012-11-05 14:22:27 [SEVERE]    at com.alk.serializers.SQLSerializer.executeQuery(SQLSerializer.java:239)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.serializers.SQLInstance.getRecord(SQLInstance.java:293)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.controllers.TrackerImpl.load(TrackerImpl.java:93)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.controllers.TrackerImpl.load(TrackerImpl.java:38)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.util.Cache.get(Cache.java:111)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.util.Cache.get(Cache.java:162)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.controllers.TrackerImpl.loadStat(TrackerImpl.java:280)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.tracker.controllers.TrackerImpl.loadRecord(TrackerImpl.java:277)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.util.BTInterface.loadRecord(BTInterface.java:44)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.util.BTInterface.loadRecord(BTInterface.java:130)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.getStat(MessageFormatter.java:345)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.formatTeamName(MessageFormatter.java:370)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.formatCommonOptions(MessageFormatter.java:99)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendMessageToTeams(MatchMessageImpl.java:60)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendOnPreStartMsg(MatchMessageImpl.java:40)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessager.sendOnPreStartMsg(MatchMessager.java:34)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.competition.match.Match.preStartMatch(Match.java:237)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.competition.match.Match.run(Match.java:191)
2012-11-05 14:22:27 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
2012-11-05 14:22:27 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:523)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:487)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
2012-11-05 14:22:27 [SEVERE] java.lang.NullPointerException
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.formatTeamName(MessageFormatter.java:370)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.formatCommonOptions(MessageFormatter.java:99)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendMessageToTeams(MatchMessageImpl.java:60)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendOnPreStartMsg(MatchMessageImpl.java:40)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessager.sendOnPreStartMsg(MatchMessager.java:34)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.competition.match.Match.preStartMatch(Match.java:237)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.competition.match.Match.run(Match.java:191)
2012-11-05 14:22:27 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
2012-11-05 14:22:27 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:523)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:487)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)

Also:
2012-11-05 14:22:27 [SEVERE] java.lang.NullPointerException
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.formatTeamName(MessageFormatter.java:370)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MessageFormatter.formatCommonOptions(MessageFormatter.java:96)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendMessageToTeams(MatchMessageImpl.java:60)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendOnPreStartMsg(MatchMessageImpl.java:40)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.controllers.messaging.MatchMessager.sendOnPreStartMsg(MatchMessager.java:34)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.competition.match.Match.preStartMatch(Match.java:237)
2012-11-05 14:22:27 [SEVERE]    at mc.alk.arena.competition.match.Match.run(Match.java:191)
2012-11-05 14:22:27 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
2012-11-05 14:22:27 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:523)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:487)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
2012-11-05 14:22:27 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
2012-11-05 14:22:27 [INFO] ^[[33;22m^[[37;1m[Paintball]^[[33;1m {teamshort1}^[[33;22m vs {teamshort2}^[[33;22m!^[[m

**Comment by freakyy85** [comment]
A server restart seems to have fixed this. Also im now using the latest downloadable BattleArena.jar from you.

**Comment by alkarinv** [comment]
I think I have a fix for this issue in the new BattleTracker.  But what happened is you went 11 hours without using the database, so the connection auto timed out.  Then when you finally started to use it again the connection was timed out and broken.

I think I have found the switch to auto reconnect, hopefully that works.  I'll put up the new BattleTracker today sometime.
