### ISSUE TITLE
Arena duel not working when teamSize: 2+

### ISSUE THREAD

**Issue by darrenstraight** [alkarinv/BattleArena#66]
"/arena duel playername" does not seem to work if arena "teamSize" is set to "teamSize: 2+" or above.

It says on your side you have set a challenge and on their side they get can /arena accept and it says they accepted it... but nothing happens, you do not get teleported into the arena or wait room (have tried with or without).

If you try /arena leave becuase nothing happens you get: An internal error occured while attempting to perform this command.

Have checked server log files:

2012-11-11 11:21:51 [INFO] darrenstraight issued server command: /arena leave
2012-11-11 11:21:51 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'arena' in plugin BattleArena v3.7.2.3
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:185)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:504)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:911)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:824)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:806)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:111)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:578)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:495)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:428)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
Caused by: java.lang.NoClassDefFoundError: com/alk/util/Log
    at mc.alk.arena.executors.CustomCommandExecutor.onCommand(CustomCommandExecutor.java:179)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more

Now if I set arena "teamSize: 1+" it does work, though it says when you in wait room "[Arena] Participants: null, null, darrenstraight, other_player_name_here" which is odd.

By setup which worked fine before for duels is as follows (with correct spacing!):

arena:
    enabled: true
    type: arena
    database: arena
    rated: true
    secondsTillBegin: 30
    secondsTillMatch: 30
    secondsToLoot: 0
    matchTime: 300
    matchUpdateInterval: 30
    prefix: "&6[Arena]&e"
    nTeams: 2+
    teamSize: 2+
    onJoin:
        options: [pvpOff]
    preReqs:
        options: [clearInventory]
    onPrestart:
        options: [pvpOff, teleportWaitroom]
    onStart:
        options: [teleportIn, pvpOn, blockBreakOff, woolTeams]
    onSpawn:
        options: [deEnchant, giveItems, hunger=20, health=20]
        giveClass:
            default: gladiator
        items: # ignored if options doesnt have "giveItems"
            - bread: 5
    onDeath:
        options: [clearInventory]
    onComplete:
        options: [teleportOut, deEnchant, clearInventory]
    winner:
        options: [health=20, hunger=20]

Thanks,
Darren

**Comment by alkarinv** [comment]
Ugh, so I accidentally included a class from another project with the same name as mine.  

Use the most recent download here on github and it should fix this.... sorry :(
