### ISSUE TITLE
BattleTracker timeouts

### ISSUE THREAD

**Issue by freakyy85** [alkarinv/BattleArena#71]
2012-11-22 10:34:08 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 30,989,949 milliseconds ago.  The last packet sent successfully to the server was 8 milliseconds ago.
2012-11-22 10:34:08 [SEVERE]    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2012-11-22 10:34:08 [SEVERE]    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
2012-11-22 10:34:08 [SEVERE]    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
2012-11-22 10:34:08 [SEVERE]    at java.lang.reflect.Constructor.newInstance(Unknown Source)
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082)
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968)
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516)
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:5022)
2012-11-22 10:34:08 [SEVERE]    at org.apache.commons.dbcp.DelegatingConnection.setAutoCommit(DelegatingConnection.java:371)
2012-11-22 10:34:08 [SEVERE]    at org.apache.commons.dbcp.DelegatingConnection.setAutoCommit(DelegatingConnection.java:371)
2012-11-22 10:34:08 [SEVERE]    at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.setAutoCommit(PoolingDataSource.java:328)
2012-11-22 10:34:08 [SEVERE]    at com.alk.serializers.SQLSerializer.getConnection(SQLSerializer.java:98)
2012-11-22 10:34:08 [SEVERE]    at com.alk.serializers.SQLSerializer.getConnection(SQLSerializer.java:91)
2012-11-22 10:34:08 [SEVERE]    at com.alk.serializers.SQLSerializer.executeBatch(SQLSerializer.java:254)
2012-11-22 10:34:08 [SEVERE]    at mc.alk.tracker.serializers.SQLInstance.saveTotals(SQLInstance.java:440)
2012-11-22 10:34:08 [SEVERE]    at mc.alk.tracker.serializers.SQLInstance.saveAll(SQLInstance.java:358)
2012-11-22 10:34:08 [SEVERE]    at mc.alk.tracker.controllers.TrackerImpl.save(TrackerImpl.java:111)
2012-11-22 10:34:08 [SEVERE]    at mc.alk.tracker.util.Cache.save(Cache.java:280)
2012-11-22 10:34:08 [SEVERE]    at mc.alk.tracker.util.Cache.flush(Cache.java:296)
2012-11-22 10:34:08 [SEVERE]    at mc.alk.tracker.controllers.TrackerImpl.flush(TrackerImpl.java:343)
2012-11-22 10:34:08 [SEVERE]    at mc.alk.tracker.Tracker.saveStats(Tracker.java:53)
2012-11-22 10:34:08 [SEVERE]    at mc.alk.tracker.Tracker.onDisable(Tracker.java:43)
2012-11-22 10:34:08 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
2012-11-22 10:34:08 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:400)
2012-11-22 10:34:08 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
2012-11-22 10:34:08 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
2012-11-22 10:34:08 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:295)
2012-11-22 10:34:08 [SEVERE]    at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:350)
2012-11-22 10:34:08 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
2012-11-22 10:34:08 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
2012-11-22 10:34:08 [SEVERE] Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529)
2012-11-22 10:34:08 [SEVERE]    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979)

I get this everytime I shut down my server in the morning. ;D

**Comment by alkarinv** [comment]
Try using this. It's a auto reconnect issue when something times out.. Hopefully this fixes it.

https://github.com/downloads/alkarinv/BattleTracker/BattleTracker.jar
