### ISSUE TITLE
/arena join error

### ISSUE THREAD

**Issue by ZeegCL** [alkarinv/BattleArena#79]
Hi, I'm getting an exception when a player tries to join an arena with /arena join arenaname or /arena join (actually, we have just 1 arena). Also, the command show the player that he is already on the queue, but if they use /arena leave, it says that he is not on queue.

/arena reload doesn't work.

I tried upgrading to v3.7.7.5, but it was broken from the onLoad()

Details:

2012-12-14 22:18:47 [SEVERE] [BA Error] [BattleArena v3.7.7.4]:public boolean mc.alk.arena.executors.BAExecutor.join(mc.alk.arena.objects.ArenaPlayer,mc.alk.arena.objects.MatchParams,java.lang.String[]) : mc.alk.arena.executors.BAExecutor@6ed22593  : mc.alk.arena.executors.CustomCommandExecutor$Arguments@20bf9d49
2012-12-14 22:18:47 [SEVERE] [BA Error] object=mc.alk.arena.objects.ArenaPlayer@659d536
2012-12-14 22:18:47 [SEVERE] [BA Error] object=Arena:arena:Arena rating=RATED,nteams=2+,teamSize=1+,vc=ONETEAMLEFT
2012-12-14 22:18:47 [SEVERE] [BA Error] object=[Ljava.lang.String;@3ef346b
2012-12-14 22:18:47 [SEVERE] java.lang.reflect.InvocationTargetException
2012-12-14 22:18:47 [SEVERE]    at sun.reflect.GeneratedMethodAccessor512.invoke(Unknown Source)
2012-12-14 22:18:47 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2012-12-14 22:18:47 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
2012-12-14 22:18:47 [SEVERE]    at mc.alk.arena.executors.CustomCommandExecutor.onCommand(CustomCommandExecutor.java:170)
2012-12-14 22:18:47 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2012-12-14 22:18:47 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
2012-12-14 22:18:47 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:985)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:903)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:858)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:113)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.ServerConnection.b(SourceFile:39)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
2012-12-14 22:18:47 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
2012-12-14 22:18:47 [SEVERE] Caused by: java.lang.NullPointerException
2012-12-14 22:18:47 [SEVERE]    at mc.alk.arena.objects.options.JoinOptions.matches(JoinOptions.java:66)
2012-12-14 22:18:47 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch(ArenaMatchQueue.java:334)
2012-12-14 22:18:47 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch(ArenaMatchQueue.java:272)
2012-12-14 22:18:47 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.notifyIfNeeded(ArenaMatchQueue.java:190)
2012-12-14 22:18:47 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.addToQueue(ArenaMatchQueue.java:117)
2012-12-14 22:18:47 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.add(ArenaMatchQueue.java:88)
2012-12-14 22:18:47 [SEVERE]    at mc.alk.arena.controllers.BattleArenaController.addToQue(BattleArenaController.java:146)
2012-12-14 22:18:47 [SEVERE]    at mc.alk.arena.executors.BAExecutor.join(BAExecutor.java:233)
2012-12-14 22:18:47 [SEVERE]    at mc.alk.arena.executors.BAExecutor.join(BAExecutor.java:139)
2012-12-14 22:18:47 [SEVERE]    ... 20 more

**Comment by alkarinv** [comment]
Hey man, sorry about the error, try this link

http://dev.bukkit.org/media/files/656/977/BattleArena.jar

If that doesn't work give me your ip so I can get on and see directly, should be able to code up a fix then.

**Comment by ZeegCL** [comment]
Hi, I started yesterday a host change, so I couldn't answer due to the file transfer stuff. I will test the file once I have my server up again :)

**Comment by alkarinv** [comment]
cool deal, let me know !

**Comment by ZeegCL** [comment]
Hi, I tested the file you gave me, after a long time (a couple of hours) the plugin failed again. This is the exception detail:

2012-12-17 21:20:54 [INFO] StyleS2 issued server command: /a join
2012-12-17 21:20:54 [SEVERE] [BA Error] [BattleArena v3.7.7.6]:public boolean mc.alk.arena.executors.BAExecutor.join(mc.alk.arena.objects.ArenaPlayer,mc.alk.arena.objects.MatchParams,java.lang.String[]) : mc.alk.arena.executors.BAExecutor@3416e08b  : mc.alk.arena.executors.CustomCommandExecutor$Arguments@58533980
2012-12-17 21:20:54 [SEVERE] [BA Error] object=mc.alk.arena.objects.ArenaPlayer@f3731790
2012-12-17 21:20:54 [SEVERE] [BA Error] object=Arena:arena:Arena rating=RATED,nteams=2+,teamSize=1+,vc=ONETEAMLEFT
2012-12-17 21:20:54 [SEVERE] [BA Error] object=[Ljava.lang.String;@3fe42fcd
2012-12-17 21:20:54 [SEVERE] java.lang.reflect.InvocationTargetException
2012-12-17 21:20:54 [SEVERE]    at sun.reflect.GeneratedMethodAccessor234.invoke(Unknown Source)
2012-12-17 21:20:54 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-12-17 21:20:54 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2012-12-17 21:20:54 [SEVERE]    at mc.alk.arena.executors.CustomCommandExecutor.onCommand(CustomCommandExecutor.java:169)
2012-12-17 21:20:54 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2012-12-17 21:20:54 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
2012-12-17 21:20:54 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:985)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:903)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:858)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:113)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.ServerConnection.b(SourceFile:39)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
2012-12-17 21:20:54 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
2012-12-17 21:20:54 [SEVERE] Caused by: java.lang.NullPointerException
2012-12-17 21:20:54 [SEVERE]    at mc.alk.arena.objects.options.JoinOptions.matches(JoinOptions.java:66)
2012-12-17 21:20:54 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch(ArenaMatchQueue.java:334)
2012-12-17 21:20:54 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch(ArenaMatchQueue.java:272)
2012-12-17 21:20:54 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.notifyIfNeeded(ArenaMatchQueue.java:190)
2012-12-17 21:20:54 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.addToQueue(ArenaMatchQueue.java:117)
2012-12-17 21:20:54 [SEVERE]    at mc.alk.arena.objects.queues.ArenaMatchQueue.add(ArenaMatchQueue.java:88)
2012-12-17 21:20:54 [SEVERE]    at mc.alk.arena.controllers.BattleArenaController.addToQue(BattleArenaController.java:146)
2012-12-17 21:20:54 [SEVERE]    at mc.alk.arena.executors.BAExecutor.join(BAExecutor.java:233)
2012-12-17 21:20:54 [SEVERE]    at mc.alk.arena.executors.BAExecutor.join(BAExecutor.java:139)
2012-12-17 21:20:54 [SEVERE]    ... 20 more

I think "vc=ONETEAMLEFT" can be a clue.

Anyways, please reopen this issue, and my server's IP is: 63.143.32.34   (haven't configured the DNS yet). Is a spanish server, so you will be the only one talking english. When you log in just use /helpop and say that you have to solve an issue with Deku, I will answer from console if logged in.

**Comment by ZeegCL** [comment]
I must add that the issue fixes everytime I restart the server, but the error comes after anyways.

**Comment by alkarinv** [comment]
Alright, how about this then. v3.7.7.7.1, this one should fix hopefully.

http://dl.dropbox.com/u/38069770/jars/BattleArena.jar

**Comment by ZeegCL** [comment]
Downloaded, if this version is right, the test will take a while, so please wait.

**Comment by alkarinv** [comment]
I'll be patient.  Thanks Deku

**Comment by ZeegCL** [comment]
This version is working fine. Great job, keep going :+1: 
This will be a permanent plugin on my server, so I hope you don't stop developing :)
